- hosts: workstation
  become: true
  remote_user: me
  roles:
    - certs-etcd-role

- hosts: k8s_control_planes:k8s_workers
  become: true
  roles:
    - k8s-prerequisites-role


- hosts: k8s_haproxy
  become: true
  remote_user: me
  vars:
    # virtual_ip: 172.40.41.1
    keepalived:
      interface: eth1
  roles:
    - haproxy-keepalived-role


- hosts: k8s_etcd
  remote_user: me
  vars:
    HOME: /home/me
  roles:
   - etcd-role


- hosts: k8s_control_planes
  remote_user: me
  vars:
    HOME: /home/me   
  roles:
   - control-plane-role

- hosts: k8s_workers
  remote_user: me
  vars:
    HOME: /home/me   
  roles:
   - worker-role
