---
- name: Gather instance facts
  setup:

- name: Install CRI-O
  include_tasks: ./tasks/CRI-O.yml

- name: Install K8s
  include_tasks: ./tasks/K8s.yml

- name: Add Load Balancer DNS
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ load_balancer.dns }}$'
    line: "{{ load_balancer.virtual_ip }} {{ load_balancer.dns }}"
    state: present