---
# tasks file for certs-etcd-role

- name: Gather instance facts
  setup:

- name: Download cfssl required binaries
  script: certs-etcd-role/files/cfssl-binaries.sh

- name: Create a Certificate Authority (CA)
  script:  certs-etcd-role/files/generate-ca-cert.sh
  
- name: Generate configuration file
  template:
    src: templates/etcd-csr.json.j2
    dest: "/home/{{ user }}/certs/etcd-csr.json"

- name: Create TLS certificates
  script:  certs-etcd-role/files/create-certs.sh

- name: Create Kubernetes certificates folder 
  file:
    path: "/home/{{ user }}/k8s-certs"
    state: directory

- name: Move certs to Home
  become: true
  copy:
    src: certs/{{ item }}
    dest: "/home/{{ user }}/k8s-certs"
  with_items:
  - ca.pem
  - etcd.pem
  - etcd-key.pem
  
- name: Change Certs files ownership 
  shell: "command sudo chown {{ user }}:{{ user }} /home/{{ user }}/k8s-certs/*"
    
